notifications:
  email: false
dist: trusty
language: cpp
sudo: required
compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7
  - wget https://github.com/philsquared/Catch/releases/download/v1.9.4/catch.hpp

script:
  - make testRunner
  - ./testRunner
